server:
  port: 8080
spring:
  web-flux:
    base-path: "/price-evaluator"
  application:
    name: "price-evaluator"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:test"
    username: "sa"
    password: "pass"
    driverClassName: "org.h2.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.H2Dialect"
  cache:
    cache-names: prices
    caffeine:
      spec: maximumSize=100,expireAfterWrite=5m
management:
  endpoints:
    web:
      exposure:
        include: "health"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:8082,http://localhost:8092,http://localhost:8080"
